remote_theme: jekyll/minima
markdown: kramdown

# Site settings
title: Usefull topics by Selvaklnc
description: >- # this means to ignore newlines until "baseurl:"
  Interesting topics with short description and title with a shortcut to the topic.
url: "https://selvaklnc.github.io/topics" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

plugins:
  - jekyll-seo-tag
